### ISSUE TITLE
No JAR Download

### ISSUE THREAD

**Issue by lukeramsden** [thebombzen/ThebombzenAPI#3]

**Comment by Traneptora** [comment]
The download link to the Dropbox site is broken, I am aware of this. I'm in the process of moving it over to Github Pages and it'll be up Soon (TM).

**Comment by lukeramsden** [comment]
Awesome

**Comment by Traneptora** [comment]
Fixed. The links in the original post have been updated and work again. See [https://thebombzen.com/LegacyModReleases/](https://thebombzen.com/LegacyModReleases/).
