### ISSUE TITLE
if i download the mod for 1.8 and launch it gives this

### ISSUE THREAD

**Issue by pizzav-xyz** [thebombzen/ThebombzenAPI#8]
![image](https://user-images.githubusercontent.com/103120356/179976379-7445356e-150a-4bdc-8855-97e9de19ac29.png)

**Comment by pizzav-xyz** [comment]
my discord is Maxime#1813 higher chance that  i answer

**Comment by Traneptora** [comment]
You need the version for Minecraft 1.8.9. See https://thebombzen.com/LegacyModReleases/ThebombzenAPI/

**Comment by pizzav-xyz** [comment]
> You need the version for Minecraft 1.8.9. See https://thebombzen.com/LegacyModReleases/ThebombzenAPI/

already went there

**Comment by pizzav-xyz** [comment]
> You need the version for Minecraft 1.8.9. See https://thebombzen.com/LegacyModReleases/ThebombzenAPI/

can u just send the link for dl of 1.8.9

**Comment by pizzav-xyz** [comment]
> > You need the version for Minecraft 1.8.9. See https://thebombzen.com/LegacyModReleases/ThebombzenAPI/
> 
> can u just send the link for dl of 1.8.9

(download)

**Comment by Traneptora** [comment]
If you can't read I can't help you.
